import Link from 'next/link';
import { ArrowRight, CheckCircle2, MessageCircle, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Section, SectionHeading } from '@/components/ui/section';
import { AbstractBackground } from '@/components/marketing/abstract-background';
import { ContactForm } from '@/components/forms/contact-form';
import { MotionDiv, fadeUp } from '@/components/sections/motion';
import { caseStudies, faqs, logos, methodology, metrics, reasons, serviceItems, site, testimonials } from '@/domain/content';

export default function Home() {
  const whatsapp = `https://wa.me/${site.whatsapp}?text=Quero%20falar%20com%20a%20Omega%20Performance`;
  const schema = { '@context': 'https://schema.org', '@type': 'ProfessionalService', name: site.name, url: site.url, description: site.description, areaServed: 'BR', serviceType: serviceItems.map((service) => service.title) };
  return <main className="overflow-hidden"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="relative min-h-screen border-b border-white/10"><AbstractBackground /><video className="absolute inset-0 h-full w-full object-cover opacity-10" autoPlay muted loop playsInline poster="/og.svg"><source src="/hero.mp4" type="video/mp4" /></video><div className="relative mx-auto grid min-h-screen max-w-7xl items-center gap-12 px-6 py-28 lg:grid-cols-[1.05fr_.95fr]"><MotionDiv {...fadeUp}><p className="mb-5 inline-flex rounded-full border border-omega-gold/20 bg-omega-gold/10 px-4 py-2 text-xs font-bold uppercase tracking-[.28em] text-omega-gold">Agência premium de performance</p><h1 className="text-balance font-display text-5xl font-semibold leading-[1.02] md:text-7xl xl:text-8xl">Transformamos investimento em anúncios em crescimento previsível.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">Um sistema de aquisição para empresas que querem escalar com dados, criatividade sofisticada, páginas de alta conversão e governança financeira.</p><div className="mt-10 flex flex-col gap-4 sm:flex-row"><Button asChild size="lg"><Link href="/contato">Solicitar Diagnóstico Gratuito <ArrowRight className="h-5 w-5" /></Link></Button><Button asChild size="lg" variant="outline"><a href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle className="h-5 w-5" /> Falar no WhatsApp</a></Button></div></MotionDiv><MotionDiv {...fadeUp} transition={{ duration: .8, delay: .15 }}><div className="relative rounded-[2.5rem] border border-white/10 bg-white/[.055] p-4 shadow-[0_40px_120px_rgba(15,61,86,.45)] backdrop-blur-2xl"><div className="rounded-[2rem] border border-white/10 bg-black/70 p-5"><div className="mb-6 flex items-center justify-between"><p className="text-sm text-white/50">Omega Revenue OS</p><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">Live</span></div><div className="grid gap-4 sm:grid-cols-3">{metrics.slice(0,3).map((metric) => <div key={metric.label} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="font-display text-2xl text-omega-gold">{metric.value}</p><p className="mt-1 text-xs text-white/45">{metric.label}</p></div>)}</div><div className="mt-6 h-44 rounded-3xl border border-white/10 bg-[linear-gradient(180deg,rgba(200,169,94,.22),rgba(15,61,86,.08))] p-5"><div className="flex h-full items-end gap-3">{[40,72,58,86,66,92,78,98].map((height, index) => <div key={index} className="flex-1 rounded-t-xl bg-gold-gradient opacity-80" style={{ height: `${height}%` }} />)}</div></div><div className="mt-6 flex items-center justify-between rounded-2xl bg-white/[.04] p-4"><div><p className="text-sm text-white/50">Payback estimado</p><p className="font-display text-3xl">42 dias</p></div><TrendingUp className="h-10 w-10 text-omega-gold" /></div></div></div></MotionDiv></div></section>
    <Section className="py-12"><div className="grid gap-4 text-center text-xs font-bold tracking-[.28em] text-white/35 md:grid-cols-6">{logos.map((logo) => <span key={logo} className="rounded-full border border-white/10 bg-white/[.03] px-5 py-4">{logo}</span>)}</div></Section>
    <Section><div className="grid gap-4 md:grid-cols-4">{metrics.map((m, i) => <MotionDiv {...fadeUp} transition={{ delay: i*.08 }} key={m.label}><Card><p className="font-display text-4xl font-semibold text-omega-gold">{m.value}</p><p className="mt-2 text-sm text-white/60">{m.label}</p></Card></MotionDiv>)}</div></Section>
    <Section><SectionHeading eyebrow="Por que escolher" title="Parece consultoria estratégica. Opera como máquina de receita." description="A Omega combina rigor financeiro, estética de produto premium e execução semanal para criar crescimento mensurável." /><div className="grid gap-6 md:grid-cols-3">{reasons.map((reason) => <Card key={reason.title}><reason.icon className="mb-5 h-9 w-9 text-omega-gold" /><h3 className="font-display text-xl font-semibold">{reason.title}</h3><p className="mt-3 text-white/60">{reason.description}</p></Card>)}</div></Section>
    <Section id="servicos"><SectionHeading eyebrow="Serviços" title="Da mídia à receita: uma stack completa para escala" /><div className="grid gap-5 md:grid-cols-4">{serviceItems.map((s) => <Link href={`/${s.slug}`} key={s.slug}><Card className="h-full"><s.icon className="mb-5 h-9 w-9 text-omega-gold" /><p className="text-xs font-bold uppercase tracking-[.24em] text-white/35">{s.eyebrow}</p><h3 className="mt-3 font-display text-xl font-semibold">{s.title}</h3><p className="mt-3 text-sm text-white/60">{s.description}</p></Card></Link>)}</div></Section>
    <Section><SectionHeading eyebrow="Timeline" title="Método Omega em 5 movimentos" /><div className="relative mx-auto max-w-4xl before:absolute before:left-6 before:top-0 before:h-full before:w-px before:bg-gradient-to-b before:from-omega-gold before:to-transparent">{methodology.map((step, index) => <MotionDiv {...fadeUp} key={step} className="relative mb-5 pl-16"><span className="absolute left-0 top-0 grid h-12 w-12 place-items-center rounded-full border border-omega-gold/40 bg-black text-omega-gold">{index + 1}</span><Card><p className="text-lg text-white/80">{step}</p></Card></MotionDiv>)}</div></Section>
    <Section><SectionHeading eyebrow="Cases" title="Resultados de operações que exigem escala e controle" /><div className="grid gap-6 md:grid-cols-3">{caseStudies.map((c) => <Card key={c.id}><p className="text-sm text-white/45">{c.segment}</p><h3 className="mt-2 font-display text-2xl">{c.company}</h3><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><span className="text-white/45">ROI</span><strong className="text-right text-omega-gold">{c.roi}</strong><span className="text-white/45">CAC</span><strong className="text-right">{c.cac}</strong><span className="text-white/45">Receita</span><strong className="text-right">{c.revenue}</strong></div></Card>)}</div></Section>
    <Section><SectionHeading eyebrow="Depoimentos" title="A percepção de quem investe alto" /><div className="grid gap-6 md:grid-cols-3">{testimonials.map((t) => <Card key={t.name}><p className="text-lg leading-8 text-white/80">“{t.quote}”</p><p className="mt-6 font-semibold">{t.name}</p><p className="text-sm text-omega-gold">{t.role}</p></Card>)}</div></Section>
    <Section><SectionHeading eyebrow="FAQ" title="Perguntas frequentes" /><div className="mx-auto grid max-w-4xl gap-4">{faqs.map(([q,a]) => <Card key={q}><h3 className="flex items-center gap-3 font-semibold"><CheckCircle2 className="h-5 w-5 text-omega-gold" />{q}</h3><p className="mt-3 text-white/60">{a}</p></Card>)}</div></Section>
    <Section id="contato" className="relative"><div className="rounded-[3rem] border border-omega-gold/20 bg-[radial-gradient(circle_at_20%_0%,rgba(200,169,94,.22),transparent_28%),rgba(255,255,255,.045)] p-8 shadow-glow backdrop-blur md:p-14"><div className="grid gap-10 md:grid-cols-2"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.3em] text-omega-gold">CTA final</p><h2 className="font-display text-4xl font-semibold md:text-6xl">Vamos desenhar sua próxima fase de crescimento?</h2><p className="mt-5 text-white/65">Diagnóstico executivo para identificar perdas, oportunidades e alavancas de escala em mídia paga.</p></div><ContactForm /></div></div></Section>
  </main>;
}
