import Link from 'next/link';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Section, SectionHeading } from '@/components/ui/section';
import { Breadcrumb } from '@/components/navigation/breadcrumb';
import { caseStudies, serviceItems } from '@/domain/content';
import type { ServiceSlug } from '@/types/content';

export function ServicePage({ slug }: { slug: ServiceSlug }) {
  const service = serviceItems.find((item) => item.slug === slug)!;
  const Icon = service.icon;
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: service.title, description: service.description, provider: { '@type': 'Organization', name: 'Omega Performance' } };
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><Section className="pt-28"><Breadcrumb current={service.title} /><div className="mx-auto max-w-4xl text-center"><Icon className="mx-auto mb-6 h-14 w-14 text-omega-gold" /><p className="mb-4 text-sm font-bold uppercase tracking-[.3em] text-omega-gold">{service.eyebrow}</p><h1 className="text-balance font-display text-5xl font-semibold md:text-7xl">{service.title}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/65">{service.description}</p><Button asChild size="lg" className="mt-10"><Link href="/contato">Solicitar diagnóstico <ArrowRight className="h-5 w-5" /></Link></Button></div></Section><Section><SectionHeading eyebrow="Benefícios" title={`O que ${service.title} destrava para sua operação`} /><div className="grid gap-5 md:grid-cols-3">{service.benefits.map((benefit) => <Card key={benefit}><CheckCircle2 className="mb-5 h-7 w-7 text-omega-gold" /><p className="text-lg text-white/80">{benefit}</p></Card>)}</div></Section><Section><SectionHeading eyebrow="Como funciona" title="Processo enxuto, sênior e orientado por dados" /><div className="grid gap-4 md:grid-cols-4">{service.process.map((step, index) => <Card key={step}><p className="mb-4 text-sm text-omega-gold">0{index + 1}</p><p className="text-white/75">{step}</p></Card>)}</div></Section><Section><SectionHeading eyebrow="Cases" title="Aplicações reais do método" /><div className="grid gap-5 md:grid-cols-3">{caseStudies.map((item) => <Card key={item.id}><p className="text-white/45">{item.segment}</p><h3 className="mt-2 font-display text-2xl">{item.company}</h3><p className="mt-4 text-omega-gold">ROI {item.roi}</p><p className="mt-2 text-sm text-white/55">{item.testimonial}</p></Card>)}</div></Section><Section><SectionHeading eyebrow="FAQ" title={`Dúvidas sobre ${service.title}`} /><div className="mx-auto grid max-w-4xl gap-4">{service.faqs.map(([question, answer]) => <Card key={question}><h3 className="font-semibold">{question}</h3><p className="mt-3 text-white/60">{answer}</p></Card>)}</div></Section><Section><div className="rounded-[3rem] border border-omega-gold/20 bg-white/[.045] p-10 text-center shadow-glow"><h2 className="font-display text-4xl font-semibold">Quer saber se {service.title} é a próxima alavanca?</h2><Button asChild size="lg" className="mt-8"><Link href="/contato">Agendar diagnóstico</Link></Button></div></Section></main>;
}
